### ISSUE TITLE
module.xml not necessary

### ISSUE THREAD

**Issue by hawknewton** [mschwartau/keycloak-custom-protocol-mapper-example#2]
Thanks for creating this example, it's been extremely helpful.

You can do the same thing using the standard deployment mechanism (you don't need `module.xml` or to modify the config) if you include your dependencies in `META-INF/MANIFEST.MF`, mine looks like this:

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven 3.8.1
Built-By: hawknewton
Build-Jdk: 16.0.1
Dependencies: org.keycloak.keycloak-core, org.keycloak.keycloak-server-s
 pi, org.keycloak.keycloak-server-spi-private, org.keycloak.keycloak-ser
 vices, javax.ws.rs.api
```

The format is super-weird, a line can't be longer than 80 characters (if memory serves) and a space continues the previous line. You can have maven generate it for you:
```
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-jar-plugin</artifactId>
      <configuration>
        <archive>
          <manifestEntries>
            <Dependencies>
              org.keycloak.keycloak-core, org.keycloak.keycloak-server-spi, org.keycloak.keycloak-server-spi-private, org.keycloak.keycloak-services, javax.ws.rs.api
            </Dependencies>
          </manifestEntries>
        </archive>
      </configuration>
    </plugin>
```
Additional details are here: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.2/html/development_guide/class_loading_and_modules

This has been tested with Keycloak 14.0.0

**Comment by mschwartau** [comment]
Thank for the issue. During the keycloak 19 migration the files were removed
