### ISSUE TITLE
This is a dead repo, seems the process would not work with latest Keycloak (19 based on quarkus)

### ISSUE THREAD

**Issue by Patrick-Ding-WellSky** [mschwartau/keycloak-custom-protocol-mapper-example#3]

**Comment by mschwartau** [comment]
Thanks for the trigger, I will update this example to the latest quarkus release

**Comment by mschwartau** [comment]
I upgrade it to keycloak 19. It is still working with some (small) changes.  The code for the mapper didn't change much.

So check it out :-)

**Comment by Patrick-Ding-WellSky** [comment]
Thanks @mschwartau. I tried your updated info, it worked. Much appreciated.
